# Generated by Django 3.2.5 on 2021-07-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='book_Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_Name', models.CharField(max_length=20)),
                ('b_Cost', models.IntegerField()),
                ('b_Author', models.CharField(max_length=20)),
            ],
        ),
    ]
