# Generated by Django 3.2.5 on 2021-08-02 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Building_Model',
            new_name='Build_Model',
        ),
        migrations.AlterModelTable(
            name='build_model',
            table='Build_Details',
        ),
    ]
